import { useLocation, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import MyHeader from "../../../../components/MyHeader";
import Sidebar from "../../../../components/Sidebar";
import Nav from "../../single_user/Nav";
import { Link } from "react-router-dom";
import { PATHS } from "../../../../router";
import { formatDate } from "../../../../utils/DateFormatter";
import printContent from "../../../../utils/printContent";
import FetchAllEmployeeForms from "../../../../controller/admin/AllFormsController";
import Spinner from "../../../../components/Spinner";
import exportToWord from "../../../../utils/exportToWord";

export default function SignedReportingForms() {
  const location = useLocation();
  const { username } = useParams();
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const apiBase = import.meta.env.VITE_API_URL;
  const [allForms, setAllForms] = useState([]);

  useEffect(() => {
    FetchAllEmployeeForms(
      setLoading,
      setErrors,
      setAllForms,
      apiBase,
      username
    );
  }, []);

  const fullname = allForms?.application_form?.profile?.full_name;
  const data = allForms?.reporting;
  const title = "Reporting: Abuse/neglect/Exploitation";

  return (
    <>
      <title>Reporting: Abuse/neglect/Exploitation - 1staccess Home Care</title>
      <div id="main-wrapper">
        <MyHeader />
        <Sidebar />
        <div className="content-body">
          <div className="container">
            <div className="page-title">
              <div className="row align-items-center justify-content-between">
                <div className="col-md-6">
                  <div className="page-title-content">
                    <h3>{username}</h3>
                    <p className="mb-2">Manage all forms signed by user</p>
                  </div>
                </div>
                <div className="col-auto">
                  <div className="breadcrumbs">
                    <a href="#">Profile </a>
                    <span>
                      <i className="ri-arrow-right-s-line"></i>
                    </span>
                    <a href="#">Forms</a>
                  </div>
                </div>
              </div>
            </div>

            <div className="row">
              <Nav username={username} />
              {loading ? (
                <Spinner />
              ) : (
                <div className="col-md-9">
                  <div class="card">
                    <div id="printArea" class="card-body">
                      {/*  */}
                      <div style={{ textAlign: "center" }}>
                        <img
                          src="/assets/images/main_logo.png"
                          width={200}
                          alt="Company Logo"
                        />
                        <h5 className="mt-10">
                          1st Access Home Care Incorporated
                        </h5>
                        <p>
                          6600 Fieldtan Trail, Moseley, VA, 23120 <br />
                          Agency Phone: (+1) 804-818-3216
                        </p>
                        <h4 className="mt-4 mb-3">
                          {" "}
                          Reporting: Abuse/neglect/Exploitation
                        </h4>
                      </div>
                      {/*  */}
                      <div className="step-content">
                        <h4 className="step-title"></h4>
                        <div className="row">
                          <div className="col-md-12">
                            <p>
                              Employee Name: <u>{fullname ?? "N/A"}</u>
                            </p>

                            <p>
                              As an employee of 1st Access Home Care, you will
                              be in receipt of confidential information. This
                              information shall include but not limited to,
                              procedures manuals, in-house policies, patient
                              lists, patient’s medical records, financial
                              information and billing records, certifications
                              and applications, actual and prospective markets
                              and patient’s business plans, client's
                              information, and any other confidential
                              information gathered, revealed, acquired or
                              generated by or for 1st Access Home Care. As an
                              employee, you shall protect and hold in confidence
                              all confidential information unless with the
                              consent of the Administrator. I acknowledge and
                              understand the competitive sensitivity of the
                              confidential information and the potential for
                              significant material harm that could result to1st
                              Access Home Care in the event that confidential
                              information is disseminated to others, in
                              particular competitors. Therefore I agree that the
                              appropriate remedy would be an immediate
                              injunction against the violating employee to
                              further prohibite the use and continued
                              dissemination of the confidential information.
                              Each employee agrees to pay 1st Access Home Care
                              in any action to enforce this confidentiality
                              agreement or cost of litigation, including
                              attorney’s fees and other damages found by the
                              trier fact.
                            </p>
                            <p>
                              As consideration for employment and for the
                              release of this confidential information, the
                              employee agrees not to compete against 1st Access
                              Home Care or to utilize any of the confidential
                              information for a period of two (2) years from the
                              date of their terminated employment with 1st
                              Access Home Care. This Non-Compete Agreement shall
                              be limited to Richmond County and contiguous
                              counties. This Non-Compete Agreement is not
                              intended to prohibit from working as a nurse,
                              therapist or other position in the health service
                              industries but is intended to prohibit employee
                              from working with a competitor of 1st Access Home
                              Care in the home health industry and utilizing any
                              of the confidential information of 1st Access Home
                              Care or contacting any of 1st Access Home Care
                              patients. Employees agree and warrant that they
                              will not contact, engage, discuss, negotiate or
                              contract with any patient or their family member
                              for the purposes of developing or promoting home
                              health care services of said patient. All parties
                              acknowledge that this confidential information is
                              of a proprietary nature to 1st Access Home Care
                              and if the confidential information is revealed to
                              the general public or to a competitor, the
                              revelation would destroy or impair the expected
                              success of 1st Access Home Care.
                            </p>
                            <p>
                              <strong style={{fontSize: "11px"}}>
                                *ANY CONTROVERSY OR CLAIM ARISING OUT OF OR
                                RELATING TO THIS AGREEMENT SHALL BE SUBMITTED TO
                                ARBITRATION BEFORE ONE(1) ARBITRATOR IN
                                RICHMOND, VIRGINIA IN ACCORDANCE WITH THE
                                COMMERCIAL ARBITRATION RULES OF THE AMERICAN
                                ARBITRATION ASSOCIATION JUDGEMENT UPON THE AWARD
                                RENDERED BY THE ARBITRATOR MAY BE ENTERED BY ANY
                                COURT HAVING JURISDICTION THEREOF. ARBITRATION
                                SHALL BE THE EXCLUSIVE, FINAL AND BINDING METHOD
                                OF RESOLUTION OF ANY CLAIM OR CONTROVERSY
                                BETWEEN 1st Access Home Care AND EMPLOYEE
                                ARISING FROM THIS AGREEMENT
                              </strong>
                            </p>
                            <p>
                              I HAVE READ AND UNDERSTAND THE ABOVE AND WILL
                              COMPLY WITH THIS AGREEMENT.
                            </p>
                          </div>
                        </div>
                        <div id="signature-wrapper" className="no-break">
                          <div id="signature-row" className="row">
                            {/* Normal layout for screen */}
                            <div className="col-md-6 d-print-none">
                              <p>Signature:</p>
                              {data?.signature ? (
                                <img
                                className="signature"
                                  src={`${apiBase}/storage/signature/${data.signature}`}
                                  alt="Signature"
                                  style={{ width: "100px" }}
                                />
                              ) : (
                                <p>
                                  <em>No signature provided</em>
                                </p>
                              )}
                            </div>
                            <div className="col-md-6 d-print-none">
                              <p>Date Signed: </p>
                              <p>{formatDate(data?.created_at)}</p>
                            </div>

                            {/* Print-only layout */}
                            {/* <div
                              className="d-none d-print-block"
                              style={{ width: "100%" }}
                            >
                              <table style={{ width: "100%", border: "none" }}>
                                <tr>
                                  <td
                                    style={{
                                      width: "50%",
                                      verticalAlign: "top",
                                      padding: "10px",
                                    }}
                                  >
                                    <p>Signature:</p>
                                    {data?.signature ? (
                                      <img
                                        src={`${apiBase}/storage/signature/${data.signature}`}
                                        alt="Signature"
                                        style={{ width: "100px" }}
                                      />
                                    ) : (
                                      <p>
                                        <em>No signature provided</em>
                                      </p>
                                    )}
                                  </td>
                                  <td
                                    style={{
                                      width: "50%",
                                      verticalAlign: "top",
                                      padding: "10px",
                                    }}
                                  >
                                    <p>Date Signed: </p>
                                    <p>{formatDate(data?.created_at)}</p>
                                  </td>
                                </tr>
                              </table>
                            </div> */}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-3 mt-20">
                      <button
                        onClick={() => exportToWord({ fullname, title })}
                        className="btn btn-primary btn-lg"
                      >
                        Print
                      </button>
                      <Link
                        onClick={() => window.history.back()}
                        style={{ marginLeft: "10px" }}
                        className="btn btn-info btn-lg"
                      >
                        Back
                      </Link>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
