import { useLocation, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import MyHeader from "../../../../components/MyHeader";
import Sidebar from "../../../../components/Sidebar";
import Nav from "../../single_user/Nav";
import { Link } from "react-router-dom";
import { formatDate } from "../../../../utils/DateFormatter";
import printContent from "../../../../utils/printContent";
import FetchAllEmployeeForms from "../../../../controller/admin/AllFormsController";

export default function SignedNonCompeteForms() {
  const location = useLocation();
  const { username } = useParams();
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const apiBase = import.meta.env.VITE_API_URL;
  const [allForms, setAllForms] = useState([]);

  useEffect(() => {
    FetchAllEmployeeForms(
      setLoading,
      setErrors,
      setAllForms,
      apiBase,
      username
    );
  }, []);

  const fullname = allForms?.application_form?.profile?.full_name;
  const data = allForms?.non_compete_agreement;

  return (
    <>
      <title>Non Compete Agreement - 1staccess Home Care</title>
      <div id="main-wrapper">
        <MyHeader />
        <Sidebar />
        <div className="content-body">
          <div className="container">
            <div className="page-title">
              <div className="row align-items-center justify-content-between">
                <div className="col-md-6">
                  <div className="page-title-content">
                    <h3>{username}</h3>
                    <p className="mb-2">Manage all forms signed by user</p>
                  </div>
                </div>
                <div className="col-auto">
                  <div className="breadcrumbs">
                    <a href="#">Profile </a>
                    <span>
                      <i className="ri-arrow-right-s-line"></i>
                    </span>
                    <a href="#">Forms</a>
                  </div>
                </div>
              </div>
            </div>

            <div className="row">
              <Nav username={username} />
              {loading ? (
                <Spinner />
              ) : (
                <div className="col-md-9">
                  <div className="card">
                    <div id="printArea" className="card-body">
                      {/*  */}
                      <div style={{ textAlign: "center" }}>
                        <img
                          src="/assets/images/main_logo.png"
                          width={200}
                          alt="Company Logo"
                        />
                        <h5 className="mt-10">
                          1st Access Home Care Incorporated
                        </h5>
                        <p>
                          6600 Fieldtan Trail, Moseley, VA, 23120 <br />
                          Agency Phone: (+1) 804-818-3216
                        </p>
                        <h4 className="mt-4 mb-3">Non-Compete Agreement</h4>
                      </div>
                      {/*  */}
                      <div className="step-content">
                        <h4 className="step-title">AGREEMENT</h4>
                        <div className="row">
                          <div className="col-md-12">
                            <p>
                              Employee Name: <u>{fullname ?? "N/A"}</u>
                            </p>

                            <p>
                              As an employee of 1st Access Home Care, the
                              employee acknowledges that they will be in receipt
                              of confidential information. This information
                              shall include but not limited to, procedures
                              manuals, in-house policies, patient lists,
                              patient’s medical records, financial information
                              and billing records, certifications and
                              applications, actual and prospective markets and
                              patient’s, business plans and marketing
                              strategies, customer lists, sales and marketing
                              data, operating systems, income statements, asset
                              and liability information, financial projections
                              and any other confidential information gathered,
                              revealed, acquired or generated by or for 1st
                              Access Home Care. Each employee shall protect and
                              hold in confidence the confidential information to
                              anyone except with the express written consent of
                              Clarissa Ayensu(Administrator). The employee
                              acknowledges and understands the competitive
                              sensitivity of the confidential information and
                              the potential for significant material harm that
                              could result to 1st Access Home Care in the event
                              that confidential information is disseminated to
                              others, in particular competitors. Therefore the
                              employee agrees that the appropriate remedy would
                              be an immediate injunction against the violating
                              employee in joining and prohibiting the use and
                              continued dissemination of the confidential
                              information. Further, each employee agrees that
                              the dissemination of the confidential information
                              would cause damages for which damages could not be
                              readily ascertained and would constitute a breach
                              of duty owed by the employee to 1st Access Home
                              Care. Each employee agrees to pay 1st Access Home
                              Care in any action to enforce this confidentiality
                              agreement or cost of litigation, including
                              attorney’s fees and other damages found by the
                              trier fact.
                            </p>
                            <p>
                              {" "}
                              As consideration for employment and for the
                              release of this confidential information, the
                              employee agrees not to compete against 1st Access
                              Home Care or to utilize any of the confidential
                              information for a period of two (2) years from the
                              date of their employment terminated with 1st
                              Access Home Care. This Non-Compete Agreement shall
                              be limited to Prince William County and contiguous
                              counties. This Non-Compete Agreement is not
                              intended to prohibit from working as a nurse,
                              therapist or other position in the health service
                              industries but is intended to prohibit employee
                              from working with a competitor of 1st Access Home
                              Care in the home health industry and utilizing any
                              of the confidential information of 1st Access Home
                              Care or contacting any of 1st Access Home Care
                              patients. Employees agree and warrant that they
                              will not contact, engage, discuss, negotiate or
                              contract with any patient or family member of a
                              patient for those purposes of developing or
                              promoting home health care services of said
                              patient. All parties acknowledge that this
                              confidential information is of a proprietary
                              nature to 1st Access Home Care and if the
                              confidential information was revealed to the
                              general public or to a competitor, the revelation
                              would destroy or impair the expected success of
                              1st Access Home Care.
                            </p>
                            <p>
                              <strong>
                                *ANY CONTROVERSY OR CLAIM ARISING OUT OF OR
                                RELATING TO THIS AGREEMENT SHALL BE SUBMITTED TO
                                ARBITRATION BEFORE ONE(1) ARBITRATOR IN
                                RICHMOND, VIRGINIA IN ACCORDANCE WITH THE
                                COMMERCIAL ARBITRATION RULES OF THE AMERICAN
                                ARBITRATION ASSOCIATION JUDGEMENT UPON THE AWARD
                                RENDERED BY THE ARBITRATOR MAY BE ENTERED BY ANY
                                COURT HAVING JURISDICTION THEREOF. ARBITRATION
                                SHALL BE THE EXCLUSIVE,FINAL AND BINDING METHOD
                                OF RESOLUTION OF ANY CLAIM OR CONTROVERSY
                                BETWEEN 1st Access Home Care AND EMPLOYEE
                                ARISING FROM THIS AGREEMENT
                              </strong>
                            </p>
                            <p>
                              I HAVE READ AND UNDERSTAND THE ABOVE AND WILL
                              COMPLY WITH THIS AGREEMENT.
                            </p>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-md-6 mt-20">
                            <p>Signature:</p>
                            {data?.signature ? (
                              <img
                                src={`${apiBase}/storage/signature/${data.signature}`}
                                alt="Signature"
                                style={{ width: "300px" }}
                              />
                            ) : (
                              <p>
                                <em>No signature provided</em>
                              </p>
                            )}
                          </div>
                          <div className="col-md-6 mt-50">
                            <p>Date Signed: </p>
                            <p>{formatDate(data?.created_at)}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-3 mt-20">
                      <button
                        onClick={printContent}
                        className="btn btn-primary btn-lg"
                      >
                        Print
                      </button>
                      <Link
                        onClick={() => window.history.back()}
                        style={{ marginLeft: "10px" }}
                        className="btn btn-info btn-lg"
                      >
                        Back
                      </Link>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
